-- AlterTable
ALTER TABLE `Post` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `thumbnail` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `updatedAt` DATETIME(3) NULL;
